spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dsms?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: 
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
    level:
        org:
            hibernate: DEBUG 
#        springframework:
#            web: DEBUG
        
---
