/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui.components;

import com.dsms.db.entity.CartItem;
import javax.swing.JSpinner;

/**
 *
 * @author Mahaj
 */
public class CartReviewItemPane extends javax.swing.JPanel {

    private CartItem cartItem;
    private int serialNo;

    /**
     * Creates new form CartReviewItem
     */
    public CartReviewItemPane() {
        initComponents();
    }

    public CartReviewItemPane(int serialNo, CartItem cartItem) {
        this.serialNo= serialNo;
        this.cartItem = cartItem;
        initComponents();
        showContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        srNoLbl = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        itemNameLbl = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        itemCountSpnr = new javax.swing.JSpinner();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        itemCountLbl = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        xLbl = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        priceLbl = new javax.swing.JLabel();
        eqLbl = new javax.swing.JLabel();
        totalPriceLbl = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(filler1);

        srNoLbl.setText("01.");
        add(srNoLbl);
        add(filler2);

        itemNameLbl.setText("jLabel1");
        add(itemNameLbl);
        add(filler3);
        add(filler8);

        itemCountSpnr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        itemCountSpnr.setMaximumSize(new java.awt.Dimension(40, 20));
        itemCountSpnr.setMinimumSize(new java.awt.Dimension(40, 20));
        itemCountSpnr.setPreferredSize(new java.awt.Dimension(40, 20));
        itemCountSpnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemCountSpnrStateChanged(evt);
            }
        });
        add(itemCountSpnr);
        add(filler4);

        itemCountLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemCountLbl.setText("1");
        itemCountLbl.setMaximumSize(new java.awt.Dimension(20, 14));
        itemCountLbl.setMinimumSize(new java.awt.Dimension(20, 14));
        itemCountLbl.setPreferredSize(new java.awt.Dimension(20, 14));
        add(itemCountLbl);
        add(filler5);

        xLbl.setText("X");
        add(xLbl);
        add(filler6);

        priceLbl.setText("90.05");
        priceLbl.setMaximumSize(new java.awt.Dimension(80, 14));
        priceLbl.setMinimumSize(new java.awt.Dimension(80, 14));
        priceLbl.setPreferredSize(new java.awt.Dimension(80, 14));
        add(priceLbl);

        eqLbl.setText(" = ");
        add(eqLbl);

        totalPriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalPriceLbl.setText("90.05");
        totalPriceLbl.setMaximumSize(new java.awt.Dimension(80, 14));
        totalPriceLbl.setMinimumSize(new java.awt.Dimension(80, 14));
        totalPriceLbl.setPreferredSize(new java.awt.Dimension(80, 14));
        add(totalPriceLbl);
        add(filler9);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCountSpnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemCountSpnrStateChanged
        JSpinner spinner = (JSpinner) evt.getSource();
        int value = (int) spinner.getValue();
        itemCountLbl.setText(String.valueOf(value));
    }//GEN-LAST:event_itemCountSpnrStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eqLbl;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel itemCountLbl;
    private javax.swing.JSpinner itemCountSpnr;
    private javax.swing.JLabel itemNameLbl;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel srNoLbl;
    private javax.swing.JLabel totalPriceLbl;
    private javax.swing.JLabel xLbl;
    // End of variables declaration//GEN-END:variables

    private void showContent() {
        this.srNoLbl.setText(String.valueOf(this.serialNo));
        this.itemNameLbl.setText(this.cartItem.getItemEntity().getName());
        this.itemCountSpnr.getModel().setValue(this.cartItem.getItemCount());
        this.priceLbl.setText(String.valueOf(this.cartItem.getItemEntity().getPrice()));
        this.totalPriceLbl.setText(String.valueOf(this.cartItem.getItemCount() * this.cartItem.getItemEntity().getPrice()));
    }
}
