/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui.components;

import com.dsms.db.entity.ItemEntity;
import javax.swing.ImageIcon;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import lombok.extern.slf4j.Slf4j;
import org.kordamp.ikonli.materialdesign.MaterialDesign;

/**
 *
 * @author Mahaj
 */
@Slf4j
public class HomePageItem extends javax.swing.JPanel {
    
    public HomePageItem(ItemEntity item) {
        initComponents();
        
        try {
            BufferedImage img = ImageIO.read(new File(item.getImageUrl()));
            Dimension dimension = getScaledDimension(new Dimension(img.getWidth(), img.getHeight()), imagePanel.getPreferredSize());
            Image dimg = img.getScaledInstance((int) dimension.getWidth(), (int) dimension.getHeight(),
                    Image.SCALE_SMOOTH);
            this.imageLbl.setIcon(new ImageIcon(dimg));
        } catch (IOException e) {
            log.error("error in reading image : {}", item.getImageUrl());
        }
        this.itemCategory.setText(item.getItemCategory().toString());
        this.itemDescription.setText(item.getDesciption());
        this.itemName.setText(item.getName());
        this.itemPrice.setText(item.getPrice().toString());
        
    }
    
    public HomePageItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        imagePanel = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        itemName = new javax.swing.JLabel();
        itemCategory = new javax.swing.JLabel();
        itemDescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        itemlabel = new javax.swing.JLabel();
        itemPrice = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addToBagBtn = new com.dsms.ui.components.SidePaneJbutton();
        addToBagBtn1 = new com.dsms.ui.components.SidePaneJbutton();

        setMaximumSize(new java.awt.Dimension(65534, 32767));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(786, 246));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setBackground(new java.awt.Color(36, 37, 42));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setMaximumSize(new java.awt.Dimension(65534, 32767));
        jPanel11.setPreferredSize(new java.awt.Dimension(1024, 224));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));
        jPanel11.add(filler3);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(240, 135));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel5.add(filler1);

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setMaximumSize(new java.awt.Dimension(240, 135));
        imagePanel.setMinimumSize(new java.awt.Dimension(240, 135));
        imagePanel.setPreferredSize(new java.awt.Dimension(240, 135));
        imagePanel.setLayout(new java.awt.BorderLayout());

        imageLbl.setBackground(new java.awt.Color(255, 255, 255));
        imageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLbl.setText(" ");
        imageLbl.setAlignmentX(0.5F);
        imageLbl.setMaximumSize(new java.awt.Dimension(240, 135));
        imageLbl.setMinimumSize(new java.awt.Dimension(240, 135));
        imageLbl.setPreferredSize(new java.awt.Dimension(240, 135));
        imagePanel.add(imageLbl, java.awt.BorderLayout.CENTER);

        jPanel5.add(imagePanel);
        jPanel5.add(filler2);

        jPanel11.add(jPanel5);
        jPanel11.add(filler4);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        itemName.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        itemName.setForeground(new java.awt.Color(255, 255, 255));
        itemName.setText("ITEM Name");
        jPanel3.add(itemName);

        itemCategory.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        itemCategory.setForeground(new java.awt.Color(189, 189, 189));
        itemCategory.setText("ITEM Category");
        jPanel3.add(itemCategory);

        itemDescription.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        itemDescription.setForeground(new java.awt.Color(228, 241, 254));
        itemDescription.setText("ITEM Description");
        jPanel3.add(itemDescription);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        itemlabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        itemlabel.setForeground(new java.awt.Color(228, 241, 254));
        itemlabel.setText("Price:  ");
        jPanel1.add(itemlabel);

        itemPrice.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        itemPrice.setForeground(new java.awt.Color(228, 241, 254));
        itemPrice.setText("200");
        jPanel1.add(itemPrice);

        jPanel3.add(jPanel1);

        jPanel2.add(jPanel3);

        jPanel4.setOpaque(false);

        addToBagBtn.setBackground(new java.awt.Color(255, 255, 255));
        addToBagBtn.setText("Add to Wishlist");
        addToBagBtn.setToolTipText("Add to Wishlist");
        addToBagBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addToBagBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addToBagBtn.setIconBackgroundColor(new java.awt.Color(255, 255, 255));
        addToBagBtn.setIconColor(new java.awt.Color(68, 138, 255));
        addToBagBtn.setIconTextGap(5);
        addToBagBtn.setIkon(MaterialDesign.MDI_BOOKMARK);
        addToBagBtn.setOpaque(false);
        addToBagBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBagBtnActionPerformed(evt);
            }
        });

        addToBagBtn1.setBackground(new java.awt.Color(255, 255, 255));
        addToBagBtn1.setForeground(new java.awt.Color(36, 37, 42));
        addToBagBtn1.setText("Add to Bag");
        addToBagBtn1.setToolTipText("Add to Bag");
        addToBagBtn1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addToBagBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addToBagBtn1.setIconBackgroundColor(new java.awt.Color(255, 255, 255));
        addToBagBtn1.setIconColor(new java.awt.Color(68, 138, 255));
        addToBagBtn1.setIconTextGap(5);
        addToBagBtn1.setIkon(MaterialDesign.MDI_CART);
        addToBagBtn1.setOpaque(false);
        addToBagBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBagBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToBagBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToBagBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 146, Short.MAX_VALUE)
                .addComponent(addToBagBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addToBagBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        jPanel11.add(jPanel2);

        add(jPanel11);
    }// </editor-fold>//GEN-END:initComponents

    private void addToBagBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBagBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToBagBtnActionPerformed

    private void addToBagBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBagBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToBagBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dsms.ui.components.SidePaneJbutton addToBagBtn;
    private com.dsms.ui.components.SidePaneJbutton addToBagBtn1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel itemCategory;
    private javax.swing.JLabel itemDescription;
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel itemPrice;
    private javax.swing.JLabel itemlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private static Dimension getScaledDimension(Dimension imgSize, Dimension boundary) {
        
        int original_width = imgSize.width;
        int original_height = imgSize.height;
        int bound_width = boundary.width;
        int bound_height = boundary.height;
        int new_width = original_width;
        int new_height = original_height;

        // first check if we need to scale width
        if (original_width > bound_width) {
            //scale width to fit
            new_width = bound_width;
            //scale height to maintain aspect ratio
            new_height = (new_width * original_height) / original_width;
        }

        // then check if we need to scale even with the new height
        if (new_height > bound_height) {
            //scale height to fit instead
            new_height = bound_height;
            //scale width to maintain aspect ratio
            new_width = (new_height * original_width) / original_height;
        }
        
        return new Dimension(new_width, new_height);
    }
}
