/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui.components;

import com.dsms.db.entity.OrderEntity;

import java.time.Instant;

import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Mahaj
 */
@Slf4j
public class OrderDetailsPane extends javax.swing.JPanel {
    private OrderEntity orderEntity;

    public OrderDetailsPane() {
        initComponents();
    }
    
    public OrderDetailsPane(OrderEntity orderEntity) {
        this.orderEntity = orderEntity;
        initComponents();
        this.orderNoLbl.setText(orderEntity.getId());
        this.orderDateLbl.setText(Instant.ofEpochMilli((orderEntity.getCreatedAt()*1000)).toString());
        this.orderStatusLbl.setText(orderEntity.getOrderState().toString());
        this.orderTotalPriceLbl.setText(orderEntity.getPrice().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orderNoLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderDateLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderStatusLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        orderTotalPriceLbl = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setBackground(new java.awt.Color(36, 37, 42));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(1022, 100));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler4);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 10, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Order No");
        jPanel1.add(jLabel2);

        orderNoLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderNoLbl.setText("orderNoLbl");
        jPanel1.add(orderNoLbl);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Order Date");
        jPanel1.add(jLabel3);

        orderDateLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderDateLbl.setText("orderDateLbl");
        jPanel1.add(orderDateLbl);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Order Status");
        jPanel1.add(jLabel4);

        orderStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderStatusLbl.setText("orderStatusLbl");
        jPanel1.add(orderStatusLbl);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Total Price");
        jPanel1.add(jLabel5);

        orderTotalPriceLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderTotalPriceLbl.setText("orderTotalPriceLbl");
        jPanel1.add(orderTotalPriceLbl);

        jPanel4.add(jPanel1);
        jPanel4.add(filler3);

        jPanel11.add(jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler1);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Summery");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3);
        jPanel2.add(filler2);

        jPanel11.add(jPanel2);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jPanel5.add(jScrollPane1);

        jPanel11.add(jPanel5);

        add(jPanel11);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderDateLbl;
    private javax.swing.JLabel orderNoLbl;
    private javax.swing.JLabel orderStatusLbl;
    private javax.swing.JLabel orderTotalPriceLbl;
    // End of variables declaration//GEN-END:variables

}
