/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui.components;

import com.dsms.ui.event.model.SidePaneEvent;
import com.dsms.ui.event.SidePaneEventListner;
import java.util.ArrayList;
import java.util.List;
import com.dsms.ui.event.EventPublisher;
import java.awt.Color;

/**
 *
 * @author Mahaj
 */
public class SidePane extends javax.swing.JPanel implements EventPublisher<SidePaneEventListner, SidePaneEvent> {

    /**
     * Creates new form SidePane
     */
    public SidePane() {
        this.sidePaneEventListners = new ArrayList<>();
        initComponents();
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new com.dsms.ui.components.ImagePanel();
        jSeparator1 = new javax.swing.JSeparator();
        homeBtn = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        myAccountBtn = new javax.swing.JButton();
        wishlistBtn = new javax.swing.JButton();
        ordersBtn = new javax.swing.JButton();
        contactUsBtn = new javax.swing.JButton();
        aboutUsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 33, 89));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(imagePanel1);
        add(jSeparator1);

        homeBtn.setBackground(new java.awt.Color(255, 51, 0));
        homeBtn.setIcon(new ColorBackgroundIcon("/images/icons8-home-26.png", Color.decode("#FFFFFF")  ));
        homeBtn.setText("Home");
        homeBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        add(homeBtn);

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30.png"))); // NOI18N
        Login.setText("Login");
        Login.setPreferredSize(new java.awt.Dimension(150, 30));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        add(Login);

        myAccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-account-24.png"))); // NOI18N
        myAccountBtn.setText("My Account");
        myAccountBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        myAccountBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myAccountBtnMouseClicked(evt);
            }
        });
        add(myAccountBtn);

        wishlistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bookmark-26.png"))); // NOI18N
        wishlistBtn.setText("Wishlist");
        wishlistBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        wishlistBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wishlistBtnMouseClicked(evt);
            }
        });
        add(wishlistBtn);

        ordersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-order-history-26.png"))); // NOI18N
        ordersBtn.setText("Orders");
        ordersBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        ordersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersBtnMouseClicked(evt);
            }
        });
        add(ordersBtn);

        contactUsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-communication-26.png"))); // NOI18N
        contactUsBtn.setText("Contact US");
        contactUsBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        contactUsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactUsBtnMouseClicked(evt);
            }
        });
        add(contactUsBtn);

        aboutUsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-info-26.png"))); // NOI18N
        aboutUsBtn.setText("About Us");
        aboutUsBtn.setPreferredSize(new java.awt.Dimension(150, 30));
        aboutUsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsBtnMouseClicked(evt);
            }
        });
        add(aboutUsBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        // TODO add your handling code here:
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.HOME_BUTTON_CLICK));
    }//GEN-LAST:event_homeBtnMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.LOGIN_BUTTON_CLICK));
    }//GEN-LAST:event_LoginMouseClicked

    private void myAccountBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountBtnMouseClicked
        // TODO add your handling code here:
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.MY_ACCOUNT_BUTTON_CLICK));
    }//GEN-LAST:event_myAccountBtnMouseClicked

    private void wishlistBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistBtnMouseClicked
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.WISHLIST_BUTTON_CLICK));
    }//GEN-LAST:event_wishlistBtnMouseClicked

    private void ordersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersBtnMouseClicked
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.ORDERS_BUTTON_CLICK));
    }//GEN-LAST:event_ordersBtnMouseClicked

    private void contactUsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsBtnMouseClicked
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.CONTACT_US_BUTTON_CLICK));
    }//GEN-LAST:event_contactUsBtnMouseClicked

    private void aboutUsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsBtnMouseClicked
        publishEvent(new SidePaneEvent(evt.getSource(), SidePaneEvent.Type.ABOUT_US_BUTTON_CLICK));
    }//GEN-LAST:event_aboutUsBtnMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton aboutUsBtn;
    private javax.swing.JButton contactUsBtn;
    private javax.swing.JButton homeBtn;
    private com.dsms.ui.components.ImagePanel imagePanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton myAccountBtn;
    private javax.swing.JButton ordersBtn;
    private javax.swing.JButton wishlistBtn;
    // End of variables declaration//GEN-END:variables

    private final List<SidePaneEventListner> sidePaneEventListners;

    @Override
    public void addEventListner(SidePaneEventListner eventListner) {
        sidePaneEventListners.add(eventListner);
    }

    @Override
    public void publishEvent(SidePaneEvent eventObject) {
        sidePaneEventListners.forEach(eventListner -> eventListner.sidePaneEventOccured(eventObject));
    }
}
