/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui.components;

import java.awt.Color;

import javax.swing.JPanel;

import com.dsms.beans.EventPublisherService;
import com.dsms.enums.ItemCategory;
import com.dsms.ui.event.model.CategoryEvent;

/**
 *
 * @author Mahaj
 */
public class WishListPanel extends javax.swing.JPanel {
    
    private JPanel selectedCategoryPanel;

    /**
     * Creates new form CategoryPanel
     */
    public WishListPanel() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(131068, 117));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 43, 100));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("WISHLIST");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 830, 110));

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void updateSelectedCategory(JPanel selectedJpanel, ItemCategory itemCategory) {
    	selectedCategoryPanel.setBackground(new Color(48,63,159));
    	selectedJpanel.setBackground(new Color(68, 138, 255));
    	selectedCategoryPanel = selectedJpanel;
    	EventPublisherService.publishEvent(new  CategoryEvent(selectedJpanel, itemCategory));
    	repaint();
    	revalidate();
    	
    }
}
