/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsms.ui;

import org.springframework.data.domain.Page;

import com.dsms.beans.ContextProvider;
import com.dsms.controller.ItemController;
import com.dsms.db.entity.ItemEntity;
import com.dsms.enums.ItemCategory;
import com.dsms.ui.components.WishlistItem;

import java.awt.LayoutManager;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Collectors;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Mahaj
 */
public class HomePage extends javax.swing.JPanel {
	
	private ItemController itemController;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
    	itemController = new ItemController();
        initComponents();
        initContent();
    }


	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryPanel1 = new com.dsms.ui.components.CategoryPanel();
        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        pageBtnPane = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(categoryPanel1);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout pageBtnPaneLayout = new javax.swing.GroupLayout(pageBtnPane);
        pageBtnPane.setLayout(pageBtnPaneLayout);
        pageBtnPaneLayout.setHorizontalGroup(
            pageBtnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        pageBtnPaneLayout.setVerticalGroup(
            pageBtnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pageBtnPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pageBtnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.dsms.ui.components.CategoryPanel categoryPanel1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pageBtnPane;
    // End of variables declaration//GEN-END:variables
    
    private void initContent() {
    	Page<ItemEntity> page = itemController.getCategoryItems(ItemCategory.GARMENTS, 0, 10);
    	
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.PAGE_AXIS));
        
		 List<WishlistItem> itemList = page.getContent().stream().map(
				item -> new WishlistItem(item.getImageUrl(), item.getItemCategory(), item.getName(), item.getPrice()))
				.collect(Collectors.toList());  
		 
		// itemList.stream().forEach(i -> content.add(i));
		 Iterator<WishlistItem> itr = itemList.iterator();
		 while(itr.hasNext()) {
			 Box box = new Box(BoxLayout.LINE_AXIS);
			 box.add(itr.next());
			 if(itr.hasNext()) {
				 box.add(itr.next());
			 }
			 
			 content.add(box);
		 }
    	
		 contentPanel.add(new JScrollPane(content, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER));
		
	}
}
